version: "3.9"

services:
  app:
    container_name: my_app
    image: aplikacija
    build: .
    ports:
      - 5004:8080
    environment:
      DB_NAME: postgres  
      DB_HOST: postgres 
      DB_PORT: 5432 

    depends_on:
      - postgres

  postgres:   
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: qwert2001
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

volumes:
  pgdata: {}

